// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBook_Backend.Data;

#nullable disable

namespace MyBook_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBook_Backend.Models.DomainModels.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A journey of dreams and destiny",
                            ImageUrl = "images/books/alchemist.jpg",
                            Price = 399,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Fantasy story of a young wizard",
                            ImageUrl = "images/books/harrypotter.jpg",
                            Price = 599,
                            Title = "Harry Potter"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Classic philosophical story",
                            ImageUrl = "images/books/littleprince.jpg",
                            Price = 299,
                            Title = "The Little Prince"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "History of humankind",
                            ImageUrl = "images/books/sapiens.jpg",
                            Price = 699,
                            Title = "Sapiens"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Historical development of civilizations",
                            ImageUrl = "images/books/gunsgermssteel.jpg",
                            Price = 799,
                            Title = "Guns, Germs, and Steel"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "A new history of the world",
                            ImageUrl = "images/books/silkroads.jpg",
                            Price = 650,
                            Title = "The Silk Roads"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Classic vampire horror novel",
                            ImageUrl = "images/books/dracula.jpg",
                            Price = 450,
                            Title = "Dracula"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Terrifying horror by Stephen King",
                            ImageUrl = "images/books/it.jpg",
                            Price = 899,
                            Title = "It"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Psychological horror thriller",
                            ImageUrl = "images/books/shining.jpg",
                            Price = 750,
                            Title = "The Shining"
                        });
                });

            modelBuilder.Entity("MyBook_Backend.Models.DomainModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Story"
                        },
                        new
                        {
                            Id = 2,
                            Name = "History"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("MyBook_Backend.Models.DomainModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("MyBook_Backend.Models.DomainModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@gmail.com",
                            MobileNo = "123456789",
                            Name = "Admin user1",
                            Password = "Admin123",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "Customer@gmail.com",
                            MobileNo = "123456789",
                            Name = "Customer user1",
                            Password = "Customer123",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("MyBook_Backend.Models.DomainModels.Book", b =>
                {
                    b.HasOne("MyBook_Backend.Models.DomainModels.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyBook_Backend.Models.DomainModels.User", b =>
                {
                    b.HasOne("MyBook_Backend.Models.DomainModels.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
